name: Build and Deploy to GCP Cloud Run

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@master
      with:
        version: 'latest'
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: test-project-424206

    - name: Build Docker image
      run: |
        docker build -t gcr.io/test-project-424206/go-webapp:$GITHUB_SHA .
        docker push gcr.io/test-project-424206/go-webapp:$GITHUB_SHA