name: Develop Testing and Code Analysis

on:
  push:
    branches:
      - Testing

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Go environment
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.20

    # Install dependencies
    - name: Install dependencies
      run: |
        cd src
        go mod tidy

    # Run static code analysis
    - name: Run static code analysis
      run: |
        cd src
        go vet ./...

    # Run linting
    - name: Run linting
      run: |
        go install golang.org/x/lint/golint@latest
        golint ./...