name: Develop Testing and Code Analysis

on:
  push:
    branches:
      - Testing

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ref: Testing

    # Set up Go environment
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.22

    # Install dependencies
    - name: Install dependencies
      run: |
        cd src
        go mod tidy

    # Run static code analysis
    - name: Run static code analysis
      run: |
        cd src
        cat main.go
        go vet ./...
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: Testing
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: Check branch name
        run: |
          echo "Branch name is $GITHUB_REF"
          cat src/main.go
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          working-directory: src
          args: --config=../.golangci.yml